services:
  web:
    image: nginx:latest # Using the default Nginx image with custom configuration.
    volumes:
      # Mount the application code for live updates
      - ./web/dist:/usr/share/nginx/html:ro
      # Mount the Nginx configuration file
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=localhost
    networks:
      - traefik-proxy
      - TownRed
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.townred.rule=Host(`townred.rainysundays.co.uk`) || Host(`www.townred.rainysundays.co.uk`)
      - traefik.http.routers.townred.entrypoints=websecure
      - traefik.http.routers.townred.tls=true
      - traefik.http.routers.townred.tls.certresolver=letsencrypt
      - traefik.http.services.townred.loadbalancer.server.port=80


networks:
  TownRed:
  traefik-proxy:
    external: true
    name: traefik-proxy

volumes:
  postgres-data-development:
